"""
Turn scoring runs into task oracles.

A Harbor task needs `solution/solve.sh` so the oracle agent can prove the task is
solvable. Writing 300 of those by hand is not possible -- the one I wrote for
spring-boot-hashids took three iterations to find a Spring Boot bump, an explicit
`java.version`, and a JUnit vintage engine, and none of that generalises.

But a run that already passed *is* a solution. So the oracle is the verified
patch, applied:

    git apply /solution/strands_agent.patch && mvn -B clean verify

That also makes every exported task provably solvable, which a hand-written
oracle never guarantees.

Usage::

    python script/harvest_solutions.py
    python script/harvest_solutions.py --root bundles --tier maximal
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path
from typing import Optional

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from harness.utils.run import iter_trials  # noqa: E402

logger = logging.getLogger(__name__)

SOLVE_SH = """\
#!/bin/bash
# GENERATED by script/harvest_solutions.py -- do not edit.
#
# The oracle is a patch that already passed MigrationBench's {tier} criteria on
# this repository ({repo_id}), taken from {source}. Applying a verified patch
# means the task is provably solvable, which a hand-written oracle cannot claim.
#
# The patch is embedded rather than read from a sibling file: a harness is only
# obliged to make solve.sh itself available, and Harbor's oracle agent does not
# copy the rest of solution/ into the container.
#
# target/ is excluded because some repositories commit their build output, so the
# patch carries binary .class hunks that git apply rejects ("cannot apply binary
# patch without full index line"). They are derived artifacts that `mvn clean
# verify` regenerates, so skipping them changes nothing that is graded.
set -euo pipefail

cd /app/repo

git apply --verbose --exclude='*/target/*' --exclude='target/*' <<'{delim}'
{patch}
{delim}

mvn -B clean verify
"""


def find_best_diff(root: Path, slug: str, tier: str) -> Optional[Path]:
    """
    The patch from this repository's best passing trial.

    Prefers maximal when asked for it: a maximal patch also satisfies minimal by
    definition, since eq. (2) is eq. (1) plus r5.
    """
    best: Optional[Path] = None
    for trial in iter_trials(root):
        if Path(trial["task_id"]["path"]).name != slug:
            continue
        if trial.get("exception_info") or not trial.get("finished_at"):
            continue

        rewards = (trial.get("verifier_result") or {}).get("rewards") or {}
        if not rewards.get("maximal" if tier == "maximal" else "minimal"):
            continue

        patch = Path(trial["_dir"]) / "artifacts" / "strands_agent.patch"
        if patch.is_file() and patch.stat().st_size > 0:
            best = patch
            if rewards.get("maximal"):
                return patch        # maximal beats minimal; stop looking
    return best


def harvest(exp_dir: Path, tasks_dir: Path, tier: str, force: bool) -> tuple[int, int]:
    """Write solve.sh + strands_agent.patch into every task with a passing run."""
    slugs = sorted({
        Path(t["task_id"]["path"]).name for t in iter_trials(exp_dir)
    })
    written, skipped = 0, 0

    for slug in slugs:
        task_dir = tasks_dir / slug
        if not (task_dir / "task.toml").is_file():
            logger.warning("No task directory for %s", slug)
            continue

        solve = task_dir / "solution" / "solve.sh"
        if solve.is_file() and "GENERATED by" in solve.read_text() and not force:
            skipped += 1
            continue

        diff = find_best_diff(exp_dir, slug, tier)
        if diff is None:
            skipped += 1
            continue

        solve.parent.mkdir(parents=True, exist_ok=True)
        patch_text = diff.read_text().rstrip("\n")
        # A delimiter that cannot occur inside a unified diff.
        delim = "JMA_PATCH_EOF"
        while delim in patch_text:
            delim += "_X"
        solve.write_text(SOLVE_SH.format(
            tier=tier,
            repo_id=slug.replace("__", "/", 1),
            source=diff.parent.parent.name,
            patch=patch_text,
            delim=delim,
        ))
        solve.chmod(0o755)
        written += 1
        logger.info("%s <- %s (%d bytes)", slug, diff.parent.parent.name, diff.stat().st_size)

    return written, skipped


def main() -> None:
    parser = argparse.ArgumentParser(description="Harvest task oracles from scoring runs")
    parser.add_argument("--root", "--job-dir", dest="root",
                        default=str(REPO_ROOT / "bundles"),
                        help="A job directory under jobs/, e.g. jobs/run1")
    parser.add_argument("--tasks-dir", default=str(REPO_ROOT / "tasks"))
    parser.add_argument("--tier", default="minimal", choices=["minimal", "maximal"])
    parser.add_argument("--force", action="store_true",
                        help="Replace solutions that were already harvested")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    exp_dir = Path(args.root).expanduser().resolve()
    if not exp_dir.is_dir():
        logger.error("No such job directory: %s", exp_dir)
        sys.exit(1)

    written, skipped = harvest(exp_dir, Path(args.tasks_dir), args.tier, args.force)
    logger.info("Harvested %d solutions, skipped %d", written, skipped)


if __name__ == "__main__":
    main()
